# Generated by Django 4.2.11 on 2024-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='closint_time',
            new_name='closing_time',
        ),
    ]
