# Generated by Django 4.2.11 on 2024-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_rename_closint_time_garage_closing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
